# 异常、断言和日志
<!-- TOC -->

- [异常、断言和日志](#异常断言和日志)
    - [处理错误](#处理错误)
        - [异常分类](#异常分类)
        - [声明受查异常](#声明受查异常)
        - [如何抛出异常](#如何抛出异常)
        - [创建异常类](#创建异常类)
    - [捕获异常](#捕获异常)
        - [捕获多个异常](#捕获多个异常)
        - [再次抛出异常与异常链](#再次抛出异常与异常链)
        - [finally子句](#finally子句)
        - [带资源的try语句](#带资源的try语句)
        - [分析堆栈轨迹元素](#分析堆栈轨迹元素)
    - [使用异常机制的技巧](#使用异常机制的技巧)
    - [使用断言](#使用断言)
        - [断言的概念](#断言的概念)
        - [启用和禁用断言](#启用和禁用断言)
        - [使用断言完成参数检查](#使用断言完成参数检查)
        - [为文档假设使用断言](#为文档假设使用断言)
    - [记录日志](#记录日志)
        - [基本日志](#基本日志)
        - [高级日志](#高级日志)
        - [本地化](#本地化)
    - [调试技巧](#调试技巧)

<!-- /TOC -->
- 出现错误时应该做到：
    - 向用户通告错误
    - 保存所有的工作结构
    - 允许用户以妥善的形式退出程序

## 处理错误
- 假设在一个Java程序运行期间出现了一个错误。用户期望在出现错误时，程序能够采用一些理智的行为。如果由于出现错误而使得某些操作没有完成，程序应该：
    - 返回到一种安全状态，并能够让用户执行一些其他命令；或者
    - 允许用户保存所有操作的结果，以妥善的方式中止程序。

- 要做到这些并不容易。异常处理的任务就是将控制权从错误产生的地方转移给能够处理这些情况的错误处理器。为了能够处理异常情况，我们必须研究哪些问题需要关注:
    1. 用户输入错误
        - 检查用户输入的错误
    2. 设备错误
        - 例如打印机没有纸，打印机被关闭等
    3. 物理限制

    4. 代码错误

- 在java中，如果某个方法不能够采用正常的途径完成他的任务，就可以通过另一个路径退出方法。这种情况下，方法不返回任何值，而是`抛出`(throw)一个封装了错误信息的对象。而且会立即退出，不会继续执行下面的代码。取而代之的是，异常处理机制开始搜索能够处理这种异常状况的一场处理器(execption handler)。

### 异常分类

- 在java中，异常对象都是派生于Throwable类的一个实例。用户可以创建自己的异常类。

- Throwable分为两个子类，一个是Error，一个是Exception
```
    Throwable
Error   Exception
```
- Error类层次结构描述了JAVA运行时系统的内部错误和资源耗尽错误。应用程序不应该抛出这种类型的对象。如果出现这样的错误，除了通告给用户，并尽力使程序安全地终止之外，再也无能为力了。这种情况很少出现。

- 在设计时，我们主要关注Exception层次结构。这个层次结构又分为两个分支：
    - RuntimeException
    - 其他异常

- 区分规则使：由程序错误导致的异常属于RuntimeException，而程序本身没有错误，但是像I/O错误这类问题导致的异常属于其他异常。

- 派生于RuntimeException的异常包含：
    - 错误的类型转换
    - 数组访问越界
    - 访问Null指针

- 其他的异常包括：
    - 试图在文件尾部后面读取数据
    - 试图打开一个不存在的文件
    - 视图根据给定的字符串查找Class对象，而这个字符串表示的类不存在。

- 如果出现RuntimeException异常，那一定是你的问题。

- java将派生于Error类或RuntimeException类的所有异常称为 `非受查`(unchecked)异常，所有其他的异常称为`受查`(checked)异常。编译器将何查是否为所有的受查异常提供了一场处理器。

### 声明受查异常

- 如果遇到了无法处理的情况，那么java可以抛出一个异常。方法不仅需要告诉编译器返回什么值，还要告诉编译器可能发生什么错误。例如读取的文件可能不存在等。

- 方法应在其首部声明所有可能抛出的异常。这样可以从首部反映出这个方法可能抛出哪类受查异常。例如FileInputStream
```
public FileInputStream(String name) throws FileNotFoundException
```

- 这个声明表示有可能抛出一个FileNoFoundException异常。如果出现了这种情况，构造器就会抛出异常，系统就会开始搜索异常处理器，以便知道如何处理这个异常对象。

- 编写方法时，不必将所有可能抛出的异常都进行声明。至于什么时候需要在方法中用throws子句声明异常，什么异常必须使用throws子句声明，需要记住4种情况应该抛出异常：
    1. 调用一个抛出受查异常的方法
    2. 程序运行过程种发现错误，并且利用throw语句抛出一个受查异常
    3. 程序出现错误
    4. java虚拟机和运行时库出现的内部错误

- 如果出现前面两种情况，则必须告诉调用这个方法的程序员有可能抛出异常。

- 对于可能被他人使用的方法，应该根据异常规范(exception specification)，在方法的首部声明这个方法可能抛出的异常。
```
public Image loadImage(String s) throws IOException
```

- 如果一个方法有可能抛出多个受查异常类型，就必须在方法的首部列出所有的异常类，每个异常类之间用逗号隔开。
```
public Image loadImage(String s) throws FileNotFoundException, EOFException
```

- 不需要声明java的内部错误，也不需要声明从RuntimeException继承的非受查异常
```
void drawImage() throws  ArrayIndexOutOfBoundsException //bad style
```

- 除了声明异常之外，还可以捕获异常。这样会使异常不被抛到方法之外，也不需要throws规范。

- 如果在子类中覆盖了超类的一个方法，子类方法中声明的受查异常不能比超类方法中声明的异常更通用。(也就是不能声明超类异常的父类)

- 如果超类方法没有抛出任何受查异常，子类也不能抛出。

- 如果类中的一个方法声明将会抛出一个异常，那么这个方法可能会抛出这个类的异常，也可能抛出这个异常类的子类的异常。

### 如何抛出异常
- 假设有一个方法读文件超出了范围，这时候需要抛出异常

- 我们首先要决定抛出什么异常，然后查阅文档找到最需要的异常，例如这里应该是抛出EOFException。
```
throw new EOFException();
//or
EOFException e = new EOFException();
throw e;
```
- 将代码组合：
```
String readData() throws EOFException
{
    //do something

    if(n < len)
    {
        throw new EOFException();
    }
    return s;
}
```

- EOFException类还有一个含有一个字符串型参数的构造器。这个构造器可以更加细致的描述异常出现的情况。
```
throw new EOFException("message");
```

- 抛出异常十分简单:
    1. 找到合适的异常类

    2. 创建对象

    3. 抛出对象

- 一旦抛出异常，方法就不可能返回到调用者。所以不必为返回的默认值或错误代码担忧。

### 创建异常类
- 用户可以创建自己的异常类。只需要定义一个派生于Exception的类即可，或派生于它的子类的类。

- 习惯上，定义的类应该包含两个构造器，一个是默认的构造器，一个使带有详细信息的构造器。
```
public class ExampleException extends IOException {
    public ExampleException(){}
    public ExampleException(String msg){
        super(msg);
    }
}
```
- 现在，就可以抛出自己定义的异常类型了。
```
void readData(int i) throws ExampleException{
    if(i<10){
        throw new ExampleException("i < 10");
    }
}
```

---
## 捕获异常
- 如果某个异常发生的时候没有在任何地方进行捕获，那程序就会终止执行。并在控制台上打印出异常信息，其中包括异常的类型和堆栈的内容。

- 想要捕获一个异常，必须设置try/catch语句块。
```
try{
    code
}
catch(ExceptionType e){
    handler for this type
}
```

- 如果在try语句块中任何代码抛出了一个 `在catch子句中说明的异常类` ，那么
    1. 程序将跳过try语句块的其余代码

    2. 程序将执行catch子句中的处理器代码

- 如果在try语句块中的代码没有抛出异常，就会跳过catch子句

- 如果方法中的任何代码抛出了一个catch子句中没有声明的异常类型，那么这个方法就会立刻退出(希望调用者为这种类型的异常设计了catch子句)

- 下面给出一个读取数据的典型程序代码；
```
public void read()
{
    try{
        //do something
    }
    catch(IOException exception)
    {
        exception.printStackTrace();
    }
}
```

- 通常，最好的选择是什么都不做，而是将异常传递给调用者，如果read方法出现了错误，就让read方法的调用者去操作。如果采用这种处理方式，就必须声明方法会抛出异常
```
public void read() throws IOException
{

}
```
- 如果调用了一个抛出受查异常的方法，就必须对他进行处理，或者继续传递。

- 那种方法更好呢？通常， 应该捕获那些知道如何处理的异常，而将那些不知道怎么样处理的异常继续传递。

- 当然也有例外，如果编写一个覆盖超类的方法，而这个方法有没有抛出异常，那么这个方法就必须捕获方法代码中出现的每一个受查异常。

### 捕获多个异常
- 在一个try语句块中可以捕获多个异常类型，并对不同类型的异常做出不同的处理。可以按照下列方式对每个异常类型使用一个单独的catch子句：
```
try{
    
}
catch(FileNotFoundException e){

}
catch(UnknownHostException e){

}
catch(IOException e){

}
```

- 异常对象可能包含与一场本身有关的信息。可以通过`e.getMessage()` 得到详细的错误信息。

- 在Java 7中，同一个catch子句中可以捕获多个异常类型。如果两个异常的处理动作是一样的，就可以合并catch子句
```
try{

}catch(FileNotFoundException | UnknownHostException e){
    //do something
}
```

- 只有当捕获的异常类彼此之间不存在子类关系时才需要这个特性。

- 捕获多个异常时，异常变量隐含为`final`变量。

### 再次抛出异常与异常链
- 在catch子句中可以抛出一个异常，这样做的目的是改变异常的类型。如果开发了一个供其他程序员使用的子系统，那么，用于表示子系统故障的异常类型可能会有多种解释。

- ServletException就是这样一个异常类型的例子。执行servlet的代码可能不想知道发生错误的细节原因，但希望明确地知道servlet是否有问题。
```
try{
    access the database
}
catch(SQLException e){
    throw new ServletException("database error" + e.getMessage());
}
```

- 不过，可以有一种更好的处理方法，并且将原始异常设置为新异常的 `原因`：
```
try{
    access the database
}
catch(SQLException e){
    Throwable se = new ServletException("database error");
    se.initCause(e);
    throw se;
}
```

- 当捕获到异常时，就可以使用下面这条语句重新得到原始异常：
```
Throwable e = se.getCause();
```
- 强烈建议使用这种包装技术。这样可以让用户抛出子系统中的高级异常，而不会丢失原始异常的细节。

- 如果在一个方法中发生了一个受查异常，而不允许抛出他，那么包装技术就十分有用，我们可以捕获这个受查异常，并将它包装成一个运行时异常。

- 有时候你只想记录一个异常，再将它重新抛出，而不做任何改变：
```
try{

}catch(Exception e){
    logger.log(level, message, e);
    throw e;
}
```

- 在java 7之前，这种方法存在一个问题，假设代码在以下方法中：
```
void updateRecord() throws SQLException
```
- java编译器查看catch块中的throw语句，然后查看e的类型，绘制出这个方法可以抛出任何Excepton而不只是SQLException。现在编译器会跟踪到e来自try块，假设这个ry块中仅有的已检查异常时SQLException实例，且在catch中为改变，这样生命就是合法的。

### finally子句

- 有时候我们需要在方法退出之前回收一些资源，或者在异常终止之后处理一些操作，我们就需要用到finally语句。

- 不管是否有异常被捕获，finally子句中的代码都会被执行。
```
InputStream in = new FileInputStream();
try{

}catch(Exception e){

}
finally{
    in.close();
}
```

- 在上面这段代码中，finally总是会被执行
    1. 代码没有抛出异常，finally会被执行

    2. 抛出一个在catch捕获的异常，无论catch中还有没有抛出异常，都会执行finally

    3. 代码抛出异常，但是catch没有捕获，还是会执行finally


- try语句可以只有finally子句，而没有catch子句
```
try{

}finally{
    in.close();
}
```

- 事实上，我们认为在需要关闭资源时，用这种方式使用finally子句是不错的选择。

- 强烈建议解耦合 try/catch 和try/finally语句块，这样可以提高代码的清晰度。
```
InputStream in =;
try{
    try{

    }finally{
        in.close();
    }
}catch(Exception e){

}
```
- 内层的try语句块只有一个职责，就是确保关闭输入流。外层的try语句也只有一个职责，那就是确保报告出现的错误。这种设计方式不仅清楚，而且还具有一个功能，将会报告finally子句中出现的错误。

- 当finally 子句包含return语句时，将会出现意想不到的结果。例如利用return从try中退出，在方法返回之前，finally子句的内容将被执行。如果finally子句中也有一个return 语句，这个返回值将会覆盖原来的返回值。
```
public int f(int n){
    try{
        return n;
    }
    finally{
        return 0;
    }
}//最终返回0
```

- 有时候,finally子句也会带来麻烦。例如，清理资源的方法也有可能抛出异常。
```
try{

}finally{
    in.close();
}
```

- 假设在try语句块的代码抛出了一些非IOException的异常，这些异常只有这个方法的调用者才能够给予处理。执行finally语句，并调用close方法。而close方法本身也可能抛出IOException。当出现这种情况是，原始的异常将会丢失，转而抛出close方法的异常。

- 这回有问题，因为第一个异常可能更重要。如果你想抛出原来的异常，代码会变得极其繁琐。
```
Exception ex = null;
try{
    try{

    }catch(Exception e){
        ex = e;
        throw e;
    }
}finally{
    try{
        in.close();
    }
    catch(Exception e){
        if( ex == null){
            throw e;
        }
    }
}
```

- java 7中则不需要这么繁琐。

### 带资源的try语句

- 对于以下代码模式:
```
try{

}
finally{

}
```

- 假设资源属于一个实现了AutoCloseable接口的类，Java 7 为这种代码方式提供了一个很有用的快捷方式。AutoCloseable接口有一个方法；
```
void close() throws Exception
```
- 另外还有一个Closeable接口，是AutoCloseable的子接口，也包含一个close方法，不过抛出的是IOException。

- 带资源的try语句的最简形式：
```
try(Resource res = ...){

}
```
- 和C#中的using很像

- try块退出时，会自动调用res.close()。
```
try(Scanner in = new Scanner(new FileInputStream("/usr/share/dict/words"),"UTF-8"))
{
    while(in.hasNext()){
        System.out.println(in.next());
    }
}
```
- 这个块正常退出或存在异常都会调用in.close方法。

- 还可以指定多个资源
```
try(Scanner in = new Scanner(new FileInputStream("/usr/share/dict/words"),"UTF-8"); PrintWriter out = new PrintWriter("out.txt"))
{
    while(in.hasNext()){
        System.out.println(in.next());
    }
}
```

- 不论这个块如何退出，in和out都会关闭。

- 这种方法close抛出的异常会 `被抑制`。这些异常将自动捕获，并由addSuppressed方法增加到原来的异常。可以通过getSuppressed方法得到被抑制的异常列表。

### 分析堆栈轨迹元素

- 堆栈轨迹(stack trace)时一个方法调用过程的列表，它包含了程序执行过程中方法调用的特定位置。当java程序正常中止，没有捕获异常时，列表就会显示出来。

- 可以调用Throwable类的printStackTrace方法访问堆栈轨迹的文本描述信息。
```
Throwable t = new Throwable();
StringWriter out = new StringWriter();
t.printStackTrace(new PrintWriter(out));
String description = out.toString();
```

- 更灵活的方法是使用getStackTrace方法。他会得到StackTraceElement对象的一个数组，可以在你的程序中分析这个对象数组。
```
Throwable t = new Throwable();
StackTraceElement[] frames = t.getStackTrace();
for(StackTraceElement e : frames)
{

    e.getClassName();
    e.getFileName();
    e.getLineNumber();
    e.getMethodName();
}
```

- StackTraceElement类含有能够获得文件名和当前执行的代码行号的方法，同时，还含有能够获得类名和方法名的方法。toString方法将产生一个格式化的字符串，其中包含所获得的信息。

- 静态的Thread.getAllStackTrace方法，它可以产生所有线程的堆栈轨迹。
```
Map<Thread, StackTraceElement[]> map = Thread.getAllStackTraces();
for(Thread t : map.keySet()){
    StackTraceElement[] e = map.get(t);
}

```

---
## 使用异常机制的技巧

- 下面是异常机制的几个技巧：

1. 异常处理不能代替简单的测试

    - 作为一个示例，试着上百万次对一个空栈进行退栈操作。在实施退栈操作之前，首先查看栈是否为空。
    ```
    if(!s.isEmpty()){
        s.pop();
    }
    ```

    - 另一个方法时强行退栈，然后捕获EmptyStackException异常来告知我们不能这样做。
    ```
    try{
        s.pop();
    }catch(EmptyStackException e){

    }
    ```
    - 调用isEmpty的版本耗时646ms。捕获异常的耗时`21 739`ms。

    - 可以看出，与执行简单测试相比，捕获异常耗时是前者的2个数量级以上的差别。因此使用异常的基本规则是：只有在异常情况下使用异常机制。

2. 不要过分细化异常

    - 很多程序员习惯将每条语句分装在一个独立的try语句块中。
    ```
    PrintStream out;
    STack s;
    try{
        n = s.pop();
    }catch(EmptyStackException e){
        //
    }
    try{
        out.writeInt(n);
    }
    catch(IOException e){

    }
    ```
    - 首先代码量太多。其次如果文件出现错误很难给予派出，而且栈是空的话也不会变成非空状态。
    - 有必要把整个任务包装在一个try语句块中。当任何一个操作出现问题时，都可以取消整个任务。
    ```
    PrintStream out;
    STack s;
    try{
        n = s.pop();
        out.writeInt(n);
    }catch(EmptyStackException e){
        //
    }
    catch(IOException e){

    }
    ```
    - 这样也满足了异常处理机制的其中一个目标，将正常处理和错误处理分开。

3. 利用异常层次结构
    - 不要只抛出RuntimeException异常，应该寻找更加适当的子类或创建自己的异常类。
    - 不要只捕获Throwable异常，否则，回什程序代码更难读，更难维护。

    - 考虑受查异常和非受查异常的区别。不要为逻辑错误抛出这些异常。
    - 将一种异常转换成另一种更适合的异常时不要犹豫。

4. 不要压制异常
    - 在java中，往往强烈地倾向关闭异常。如果编写了一个调用另一个方法的方法，而这个方法有可能100年才抛出一个异常，那么，编译器会因为没有将这个异常列在throws表中产生抱怨。这时候，我们应该将这个异常关闭。
    ```
    void method(){
        try{

        }catch(Exception e){
            //
        }
    }
    ```
    - 如果认为一场非常重要，就对他们进行处理。

5. 在检测错误时。苛刻要比放任更好。
    - 例如，当栈空时，Stack.pop时返回一个null还是抛出一个异常？我们认为，在出错的地方抛出一个异常比后面抛出NullPointer异常更好。

6. 不要羞于传递异常。
    - 某些异常传递比捕获好。
    - 让高层次的方法通知用户发生了错误，或者放弃不成功的命令更适宜。

- 5/6可以归结为 `早抛出，晚捕获`。

---

## 使用断言

### 断言的概念
- 假设确信某个属性符合要求，并且代码的执行依赖于这个属性，例如，需要计算
```
double y = Math.sqrt(x);
```

- 我们确信，这里的x是一个非负数。然而，还是希望进行检查，以避免让 `不是一个数` 的数值参与计算操作。当然，也可以抛出一个异常：
```
if(x < 0){
    throw new IllegalArgumentException("x<0");
}
```
- 但是这样的代码会一直保留在程序中，即使测试完毕也不会自动地删除。如果在程序中含有大量这样的检查，程序运行会很慢。

- 断言机制允许在测试期间插入一些检查语句。当代码发布时，检测语句会自动被移走。(类似C#的 #debug?)

- Java语言引入assert关键字。有两种形式:
```
assert 条件;
和
assert 条件：表达式;
```
- 这两种形式都会对条件进行检测，如果结果为false，则抛出一个AssertionError异常。第二种形式表达式会被传入异常的构造器，转换成一个消息字符串。

### 启用和禁用断言
- 在默认情况下，断言被禁用。可以在运行程序时用-enableassertions或-ea选项启用。
```
java -enableassertions MyApp
```
- 启用或禁用断言时不必重新编译程序。启用或禁用断言时类加载器(calss loader)的功能。(代理里也用到这个)当断言被禁用时，类加载器将跳过断言代码，因此，不会降低程序运行的速度。

- P303 有详细的断言禁用启用内容

### 使用断言完成参数检查
- 在java中有3种处理系统错误的机制：
    - 抛出异常
    - 日志
    - 使用断言
- 使用断言请记住以下几点
    - 断言失败是致命的、不可恢复的错误
    - 断言检查只用于开发和测试阶段


### 为文档假设使用断言

- P305

---
## 记录日志
- 日志API有几个优点
    - 可以很容易地取消全部日志记录。或者仅仅取消某个级别的日志。而且打开和关闭这个操作也很容易。

    - 可以很简单地禁止日志记录的输出，因此，将日志代码留在程序中开销很小。

    - 日志记录可以被定向到不同的处理器，用于在控制台显式，用于存储在文件中等。

    - 日志记录器和处理器都可以对记录进行过滤。过滤器可以根据过滤实现其指定的标准丢弃那些无用的记录项。

    - 日志记录可以采用不同的方式格式化，例如，纯文本或XML。

    - 应用程序可以使用多个日志记录器，他们使用类似包名的这种具有层次结构的名字。

    - 在默认情况下，日志系统的配置由配置文件控制。如果需要，应用程序可以替换这个配置。


### 基本日志

- 简单的日志记录可以使用全局日志记录器(global logger)并调用其info方法：
```
Logger.getGlobal().info("log test");
//output
四月 18, 2019 7:41:39 下午 wuran.chapter7.log.LogTest main
信息: log test
```

- 在适当的地方(如main开始)调用
```
Logger.getGlobal().setLevel(Level.OFF);
```
- 可以按级别禁用日志。


### 高级日志
- 在一个专业的应用程序种，不要将所有的日志都记录到一个全局日志记录器中，而是可以自定义日志记录器。

- 可以调用getLogger方法创建或获取记录器。
```
static final Logger mylog = Logger.getLogger("com.mycompany.myapp");
```

- 未被任何变量引用的日志记录器可能会被垃圾回收。为了防止这种情况，要像上面的例子一样，用一个静态变量存储日志记录器的一个引用，P307

### 本地化



---
## 调试技巧
- 

- 日志代理(logging proxy)是一个子类的对象，他可以解惑放发调用，并进行日志记录，然后调用超类中的方法。

- 例如，再调用Random类的nextDouble方法时出了问题，就可以按照下面的方式，以匿名子类示例的形式创建一个代理对象。
```
Randow generator = new Random(){
    public double nextDouble(){
        double result = super.nextDobule();
        Logger.getGlobal().info("nextDouble:" + result);
        return result;
    }
}
```

- 当调用nextDouble方法时，就会产生一个日志消息。要想知道谁调用了这个方法，就要生成一个堆栈轨迹。

- 不一定要通过捕获异常来生成堆栈轨迹。还可以使用这条语句获得堆栈轨迹。
```
Thread.dumpStack();
```

- 一般来说，堆栈轨迹显示在System.err上。也可以利用printStackTrae(PrintWriter s)方法将他发送到一个文件中。另外，如果想记录或显示堆栈轨迹，可以采用下面的方法：
```
        StringWriter writer = new StringWriter();
        new Throwable().printStackTrace(new PrintWriter(writer));
        String desc = writer.toString();
        System.out.println(desc);
```

- 可以调用静态的Thread.setDefaultUncaughtExceptionHandler方法改变非捕获异常的处理器：
```
public class ExampleExceptionHandler implements Thread.UncaughtExceptionHandler {
    @Override
    public void uncaughtException(Thread t, Throwable e) {
        StringWriter writer = new StringWriter();
        e.printStackTrace(new PrintWriter(writer));
        String desc = writer.toString();
        System.out.println(desc);
        System.out.println("ExampleExceptionHandler");
    }
}
public static void main(String[] args) throws Exception {
        Thread.setDefaultUncaughtExceptionHandler(new ExampleExceptionHandler());
        readData(1);
}
```
- p324